name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.4
    steps:
      - name: say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory listing
        run: |
          ls -l